title: "Martin Desmazières"
logo: "martin.desmazieres/assets/images/profile.png"
description: "Portfolio — Data Science, Statistics & Machine Learning"
theme: jekyll-theme-minimal

show_downloads: true
