title: "Martin Desmazières"
description: "Portfolio — Data Science, Statistics & Machine Learning"

theme: jekyll-theme-minimal

# GitHub Pages

url: "https://martindesm.github.io"
baseurl: "/martin.desmazieres"

# Profile

logo: "/assets/images/profile.png"

# GitHub Pages options

show_downloads: true

# Author

author:
name: "Martin Desmazières"
